pull_request_rules:
  - name: automatic merge for master when the title contains “WIP” (ignoring case)
    conditions:
      - base=master
      - label!=work-in-progress
    actions:
      merge:
        method: merge
        commit_message: title+body
      delete_head_branch: {}
  - name: Merge pull requests from dependabot
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: merge
        commit_message: title+body
      delete_head_branch: {}
