pull_request_rules:
  - name: Merge pull requests from owner that are not a WIP
    conditions:
      - base=master
      - author=JordanSinko
      - label!=work-in-progress
    actions:
      merge:
        method: merge
        commit_message: title+body
      delete_head_branch: {}
  - name: Merge pull requests from dependabot
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: merge
        commit_message: title+body
      delete_head_branch: {}
